import { Activity, ArrowUpRight, Bot, Database, Filter, Plus, Search, SlidersHorizontal, Sparkles, TrendingUp, Zap } from "lucide-react";
import { Topbar } from "@/components/topbar";
import { ProductCard } from "@/components/product-card";
import { Button } from "@/components/ui/button";
import { mockProducts } from "@/lib/mock-data";

const stats = [{ label: "Signals scanned", value: "18,402", detail: "+12.8% this week", icon: Activity, color: "text-blue-400" }, { label: "Products discovered", value: "247", detail: "+34 new today", icon: Sparkles, color: "text-amber-400" }, { label: "Avg. trend score", value: "86.4%", detail: "+4.2% vs last month", icon: TrendingUp, color: "text-emerald-400" }, { label: "Capital protected", value: "$12.8k", detail: "from defensive kills", icon: ShieldIcon, color: "text-cyan-400" }];

function ShieldIcon({ className }: { className?: string }) { return <Database className={className} />; }

export default function Home() {
  return <div className="min-h-full bg-[#0a0c10]"><Topbar eyebrow="Product Discovery Hub" /><div className="mx-auto max-w-[1440px] px-5 py-8 sm:px-8 sm:py-10"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-4 flex items-center gap-2 text-[11px] font-medium uppercase tracking-[0.15em] text-blue-400"><span className="h-1.5 w-1.5 rounded-full bg-blue-400 shadow-[0_0_10px_rgba(96,165,250,.8)]" />Intelligence layer</div><h1 className="text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl">Product Discovery Hub</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-slate-500">Your autonomous research agent has found a fresh batch of high-conviction opportunities.</p></div><div className="flex items-center gap-2"><Button variant="outline" className="h-9 border-white/[0.1] bg-white/[0.02] text-[11px] text-slate-400 hover:bg-white/[0.06] hover:text-white"><Filter className="mr-2 h-3.5 w-3.5" />Filter signals</Button><Button className="h-9 bg-blue-500 text-[11px] text-white hover:bg-blue-400"><Plus className="mr-2 h-3.5 w-3.5" />New scan</Button></div></div>
    <div className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map((stat) => <div key={stat.label} className="rounded-xl border border-white/[0.08] bg-[#0e1117] p-4"><div className="flex items-start justify-between"><p className="text-[10px] font-medium uppercase tracking-[0.1em] text-slate-600">{stat.label}</p><stat.icon className={`h-4 w-4 ${stat.color}`} strokeWidth={1.8} /></div><p className="mt-3 font-mono text-xl font-medium tracking-tight text-white">{stat.value}</p><p className="mt-1 text-[10px] text-slate-600">{stat.detail}</p></div>)}</div>
    <div className="mt-10 flex flex-col gap-4 border-b border-white/[0.07] pb-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Bot className="h-4 w-4 text-blue-400" /><h2 className="text-sm font-medium text-slate-200">High-conviction opportunities</h2><span className="rounded-full bg-white/[0.06] px-2 py-0.5 font-mono text-[9px] text-slate-500">06</span></div><p className="mt-1 text-[11px] text-slate-600">Ranked by demand velocity, seasonal timing, regional slots, and creative saturation.</p></div><div className="flex items-center gap-2"><div className="flex h-8 items-center gap-2 rounded-lg border border-white/[0.08] bg-white/[0.02] px-2.5"><Search className="h-3.5 w-3.5 text-slate-600" /><input placeholder="Search products" className="w-28 bg-transparent text-[11px] text-slate-300 outline-none placeholder:text-slate-700" /></div><button className="rounded-lg border border-white/[0.08] p-2 text-slate-600 hover:bg-white/[0.05] hover:text-slate-300"><SlidersHorizontal className="h-3.5 w-3.5" /></button></div></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{mockProducts.map((product) => <ProductCard key={product.id} product={product} />)}</div>
    <div className="mt-8 flex items-center justify-between rounded-xl border border-white/[0.07] bg-white/[0.018] px-4 py-3"><div className="flex items-center gap-2 text-[11px] text-slate-600"><Zap className="h-3.5 w-3.5 text-amber-400" />Next automated scan in <span className="font-mono text-slate-400">04:18:32</span></div><button className="flex items-center gap-1 text-[11px] text-slate-500 hover:text-blue-400">View scan history<ArrowUpRight className="h-3 w-3" /></button></div>
  </div></div>;
}
